import {test,expect} from '@playwright/test';
test.use({channel:'chrome'});
test('quota unavailable is distinct from successful connection',async({page})=>{
 const account={id:'new',name:'New account',enabled:true,auth:'usage-unavailable',eligible:false,windows:[],error:'Usage unavailable for this credential (HTTP 403).'};
 await page.route('**/api/status',route=>route.fulfill({json:{accounts:[account],sessions:[],events:[],threshold:95,localProcesses:{processes:[]}}}));
 await page.route('**/api/accounts/verify',route=>{account.connectionCheck={ok:true,at:new Date().toISOString()};return route.fulfill({json:{ok:true,detail:'Official Claude answered a test request using this credential.'}})});
 await page.goto('http://127.0.0.1:43127');
 await expect(page.locator('.card')).toContainText('Quota unavailable');
 page.on('dialog',dialog=>dialog.accept());
 await page.getByRole('button',{name:'Test connection'}).click();
 await expect(page.locator('.card')).toContainText('Connection passed');
 await expect(page.locator('.card')).toContainText('Quota unavailable');
 await expect(page.locator('#available')).toHaveText('0 / 1');
 await expect(page.getByRole('button',{name:'Switch here'})).toBeEnabled();
});
test('six accounts, expiry warnings, external processes and mobile layout',async({page})=>{
 await page.route('**/api/status',route=>route.fulfill({json:{activeId:'0',autoSwitch:true,threshold:95,accounts:Array.from({length:6},(_,i)=>({id:String(i),name:`account-${i+1}@example.com`,enabled:true,auth:i===5?'expired':'ok',eligible:i!==5,observedAt:new Date().toISOString(),expiresAt:i===5?Date.now()-1000:Date.now()+3600000,windows:[{key:'five_hour',label:'5 hours',used:i*15,resetsAt:new Date(Date.now()+3600000).toISOString()}]})),sessions:[],events:[],localProcesses:{processes:[{pid:123,tty:'ttys001'}],error:null}}}));
 await page.goto('http://127.0.0.1:43127');
 await expect(page.locator('.card')).toHaveCount(6);
 await expect(page.locator('#available')).toHaveText('5 / 6');
 await expect(page.locator('#external-sessions')).toContainText('PID 123');
 await expect(page.locator('.card').last()).toContainText('Expired');
 await page.getByRole('button',{name:'Connect another account'}).click();
 await expect(page.getByRole('dialog')).toContainText('does not automatically renew');
 await page.getByText('02 · Paste a setup token instead').click();
 await expect(page.locator('input[name="token"]')).toBeVisible();
 await page.locator('[data-close="account-dialog"]').click();
 await page.setViewportSize({width:1440,height:1100});
 await page.evaluate(()=>window.scrollTo(0,0));
 await page.screenshot({path:'dashboard-six-preview.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await expect(page.locator('body')).toHaveJSProperty('scrollWidth',390);
});
