import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {Manager} from '../lib/manager.mjs';
import {atomicJSON,readJSON,seal} from '../lib/core.mjs';
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'switchboard-unit-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const m=new Manager(root);m.tm=async()=>'';const a={id:crypto.randomUUID(),name:'A',enabled:true,auth:'ok',observedAt:new Date().toISOString(),windows:[{key:'five_hour',used:99}]};const b={...a,id:crypto.randomUUID(),name:'B',windows:[{key:'five_hour',used:5}]};m.state.accounts=[a,b];for(const account of [a,b])atomicJSON(path.join(root,'vault',account.id+'.json'),seal({accessToken:'test-'+account.name,expiresAt:Date.now()+3600000},m.key));return {m,root,a,b}}
test('tracking refresh includes accounts disabled for switching',async t=>{const {m,a,b}=fixture(t);b.enabled=false;const refreshed=[];m.refreshAccount=async account=>refreshed.push(account.id);m.tick=async()=>{};await m.refresh();assert.deepEqual(refreshed,[a.id,b.id]);assert.equal(m.refreshing,false)});
test('revoked credentials cannot be manually selected with unknown expiration',async t=>{const {m,b}=fixture(t);b.auth='expired';await assert.rejects(m.switchTo(b.id),/Reconnect/)});
test('quota 403 preserves working auth and backs off',async t=>{const {m,a}=fixture(t);t.mock.method(globalThis,'fetch',async()=>new Response('{}',{status:403}));await m.refreshAccount(a);assert.equal(a.auth,'ok');assert.ok(a.retryAt>Date.now()+14*60000);assert.equal(a.windows[0].used,99)});
test('quota 401 marks the account expired',async t=>{const {m,a}=fixture(t);t.mock.method(globalThis,'fetch',async()=>new Response('{}',{status:401}));await m.refreshAccount(a);assert.equal(a.auth,'expired');assert.ok(a.authErrorAt)});
test('old telemetry does not revive a rejected credential',async t=>{const {m,root,a}=fixture(t);await m.switchTo(a.id);m.state.lastSwitchAt=Date.now()-61000;a.auth='expired';a.authErrorAt=Date.now();const id=crypto.randomUUID();m.state.sessions=[{id,name:'test',cwd:root,running:true}];atomicJSON(path.join(root,'telemetry',id+'.json'),{accountId:a.id,at:Date.now()-1000,windows:[{key:'five_hour',used:0}]});await m.tick();assert.equal(a.auth,'expired');assert.equal(a.windows[0].used,99)});
test('generic limit errors do not fabricate a five-hour percentage',async t=>{const {m,root,a}=fixture(t);await m.switchTo(a.id);a.windows=[];const id=crypto.randomUUID();m.state.sessions=[{id,name:'test',cwd:root,running:true}];atomicJSON(path.join(root,'activity',id+'.json'),{busy:true,accountId:a.id});const file=path.join(m.runtime,'projects',root.replace(/[^A-Za-z0-9]/g,'-'),id+'.jsonl');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify({type:'assistant',message:{id:'limit',model:'<synthetic>',content:[{type:'text',text:"You've hit your session limit"}]}})+'\n');await m.tick();assert.deepEqual(a.windows,[]);assert.ok(a.limitDetectedAt);assert.ok(a.cooldownUntil>Date.now())});
test('automatic threshold switch preserves sessions and writes only managed credentials',async t=>{const {m,root,a,b}=fixture(t);await m.switchTo(a.id);m.state.autoSwitch=true;m.state.lastSwitchAt=Date.now()-61000;const id=crypto.randomUUID();m.state.sessions=[{id,name:'test',cwd:root,running:true}];await m.tick();assert.equal(m.state.activeId,b.id);assert.equal(m.state.sessions[0].id,id);assert.equal(readJSON(path.join(root,'runtime','.credentials.json')).claudeAiOauth.accessToken,'test-B');assert.equal(fs.statSync(path.join(root,'runtime','.credentials.json')).mode&0o777,0o600)});
test('switch waits while a session is producing a response',async t=>{const {m,root,a,b}=fixture(t);await m.switchTo(a.id);const id=crypto.randomUUID();m.state.sessions=[{id,running:true}];atomicJSON(path.join(root,'activity',id+'.json'),{busy:true});await assert.rejects(m.switchTo(b.id),/working/);assert.equal(m.state.activeId,a.id)});
test('API snapshot never includes stored credential material',async t=>{const {m,a}=fixture(t);a.fingerprint='sensitive-fingerprint';const text=JSON.stringify(m.snapshot());assert.ok(!text.includes('sensitive-fingerprint'));assert.ok(!text.includes('test-A'));assert.ok(!text.includes('accessToken'))});
test('only synthetic assistant errors trigger error-driven failover',async t=>{const {m,root,a,b}=fixture(t);await m.switchTo(a.id);m.state.autoSwitch=true;m.state.lastSwitchAt=Date.now()-61000;const id=crypto.randomUUID(),cwd=root;m.state.sessions=[{id,name:'test',cwd,running:true}];atomicJSON(path.join(root,'activity',id+'.json'),{busy:true,accountId:a.id});const file=path.join(m.runtime,'projects',cwd.replace(/[^A-Za-z0-9]/g,'-'),id+'.jsonl');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify({type:'assistant',message:{id:'normal',model:'claude-haiku',content:[{type:'text',text:'Example: API Error 429 rate limit'}]}})+'\n');await m.tick();assert.equal(m.state.activeId,a.id);fs.writeFileSync(file,JSON.stringify({type:'assistant',message:{id:'synthetic',model:'<synthetic>',content:[{type:'text',text:"You've hit your limit"}]}})+'\n');await m.tick();assert.equal(m.state.activeId,b.id);assert.equal(m.state.sessions[0].waitingForAccount,true)});
