import {test,expect} from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import crypto from 'node:crypto';
const project=path.resolve(import.meta.dirname,'..');
test.use({channel:'chrome',viewport:{width:1440,height:1050}});
test('dashboard switches a real running Claude session and preserves its conversation',async({page})=>{
 test.skip(process.env.SWITCHBOARD_LIVE_TEST!=='1','Opt-in: makes real subscription requests in an existing test session.');
 test.setTimeout(90000);
 const root=path.join(project,'.state'),state=JSON.parse(fs.readFileSync(path.join(root,'state.json'))),session=state.sessions.at(-1);
 const key=fs.readFileSync(path.join(root,'dashboard.key'),'utf8');
 const socket='switchboard-'+crypto.createHash('sha256').update(root).digest('hex').slice(0,12);
 const target=state.accounts.find(a=>a.id!==state.activeId&&a.enabled&&a.auth==='ok');
 if(!target)throw Error('Connect two healthy test accounts first');
 const pid=()=>execFileSync('tmux',['-L',socket,'display-message','-p','-t',session.name,'#{pane_pid}'],{encoding:'utf8'}).trim();
 const before=pid();
 await page.addInitScript(key=>sessionStorage.setItem('switchboard-key',key),key);
 await page.goto('http://127.0.0.1:43127');
 await page.locator('.card').filter({has:page.getByRole('heading',{name:target.name,exact:true})}).getByRole('button',{name:'Switch here'}).click();
 await expect(page.locator('#selected')).toHaveText(target.name);
 // Match the conservative reload allowance verified in the isolated experiment.
 await page.waitForTimeout(35000);
 await page.getByRole('button',{name:'Open terminal'}).last().click();
 await page.locator('#message').fill('Without tools: what string did we assign to label in our previous JavaScript example? Reply in the format SWITCH-VERIFIED: <value>.');
 await page.getByRole('button',{name:'Send',exact:true}).click();
 await expect(page.locator('#terminal')).toContainText('SWITCH-VERIFIED: MAPLE-482',{timeout:35000});
 expect(pid()).toBe(before);
 const final=JSON.parse(fs.readFileSync(path.join(root,'state.json')));
 expect(final.sessions.at(-1).id).toBe(session.id);
 fs.writeFileSync(path.join(root,'live-verification.json'),JSON.stringify({verifiedAt:new Date().toISOString(),pid:before,sessionId:session.id,version:'2.1.268',result:'Browser account switch preserved native interactive process and conversation'},null,2),{mode:0o600});
 await page.locator('[data-close="terminal-dialog"]').click();
 await page.screenshot({path:path.join(project,'dashboard-preview.png'),fullPage:true});
});
