import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {NativeManager,authMetadata} from '../lib/native-manager.mjs';import {atomicJSON,cleanEnv} from '../lib/core.mjs';
function fixture(t,exec=async()=>({stdout:''})){const root=fs.mkdtempSync(path.join(os.tmpdir(),'runway-unit-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));return {root,m:new NativeManager(root,{exec,claude:'/official/claude'})}}
test('profile creation writes metadata, not credentials or a vault',t=>{const {m,root}=fixture(t);const p=m.createProfile();assert.ok(fs.existsSync(m.configDir(p.id)));assert.deepEqual(fs.readdirSync(m.configDir(p.id)),[]);assert.ok(!fs.existsSync(path.join(root,'vault.key')));assert.ok(!fs.existsSync(path.join(root,'vault')))});
test('status retains only approved official metadata',async t=>{const {m}=fixture(t,async()=>({stdout:JSON.stringify({loggedIn:true,email:'person@example.com',authMethod:'claude.ai',accessToken:'do-not-store',refreshToken:'do-not-store'})}));const p=m.createProfile();await m.checkProfile(p.id);assert.equal(p.auth.email,'person@example.com');assert.ok(!JSON.stringify(m.snapshot()).includes('do-not-store'))});
test('signed out nonzero native status is handled without collecting credentials',async t=>{const {m}=fixture(t,async()=>{throw {stdout:JSON.stringify({loggedIn:false})}});const p=m.createProfile();assert.equal((await m.checkProfile(p.id)).loggedIn,false)});
test('invalid status does not replace previous official metadata',async t=>{const {m}=fixture(t,async()=>({stdout:'{}'}));const p=m.createProfile();p.auth={loggedIn:true};await assert.rejects(m.checkProfile(p.id),/login result/);assert.equal(p.auth.loggedIn,true)});
test('login launches official auth login, not setup-token',async t=>{const calls=[];const {m}=fixture(t,async(...args)=>{calls.push(args);return {stdout:''}});const p=m.createProfile();const s=await m.startLogin(p.id);assert.equal(s.kind,'login');assert.deepEqual(calls[0][1].slice(-2),['auth','login']);assert.equal(calls[0][2].env.CLAUDE_CONFIG_DIR,m.configDir(p.id));assert.ok(!JSON.stringify(calls).includes('setup-token'));assert.equal((await m.startLogin(p.id)).id,s.id)});
test('two profiles launch with distinct configuration directories',async t=>{const calls=[];const {m,root}=fixture(t,async(...args)=>{calls.push(args);return {stdout:''}});const a=m.createProfile(),b=m.createProfile();await m.launch({profileId:a.id,cwd:root});await m.launch({profileId:b.id,cwd:root});assert.notEqual(calls[0][2].env.CLAUDE_CONFIG_DIR,calls[1][2].env.CLAUDE_CONFIG_DIR);for(const call of calls){assert.ok(call[1].includes('--session-id'));assert.ok(!call[1].includes('--dangerously-skip-permissions'))}assert.deepEqual(fs.readdirSync(m.configDir(a.id)),[])});
test('new login cannot change a profile that has running work',async t=>{const {m,root}=fixture(t);const p=m.createProfile();await m.launch({profileId:p.id,cwd:root});await assert.rejects(m.startLogin(p.id),/running work/)});
test('legacy migration reads metadata but leaves old state untouched',t=>{const {m,root}=fixture(t);const old={accounts:[{name:'old',fingerprint:'private-metadata'}],sessions:[{id:'old',cwd:'/project',name:'old'}],autoSwitch:true};atomicJSON(path.join(root,'state.json'),old);const fresh=new NativeManager(root);assert.equal(fresh.snapshot().legacy.accounts,1);assert.equal(fresh.state.profiles.length,0);assert.ok(!JSON.stringify(fresh.snapshot()).includes('private-metadata'));assert.deepEqual(JSON.parse(fs.readFileSync(path.join(root,'state.json'))),old)});
test('competing inherited token variables are not forwarded into isolated profiles',()=>{const env=cleanEnv({PATH:'/bin',ANTHROPIC_API_KEY:'secret',CLAUDE_CODE_OAUTH_TOKEN:'secret',CLAUDE_CONFIG_DIR:'/old'},'/new');assert.deepEqual(env,{PATH:'/bin',CLAUDE_CONFIG_DIR:'/new'})});
test('metadata strips unexpected secret fields',()=>{assert.deepEqual(Object.keys(authMetadata({loggedIn:true,token:'secret'})).sort(),['authMethod','checkedAt','email','loggedIn','subscriptionType'].sort())});
test('profile lookup rejects arbitrary config paths',async t=>{const {m,root}=fixture(t);assert.throws(()=>m.configDir('../../outside'),/not found/);await assert.rejects(m.launch({profileId:'../../outside',cwd:root}),/not found/)});
