import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {checkConnection} from './connection-check.mjs';
import {atomicJSON,readJSON,seal,unseal,windowsFromUsage,eligible,chooseAccount,cleanEnv,redact,retryDelay,mergeWindows} from './core.mjs';
const exec=promisify(execFile);
const quote=s=>"'"+String(s).replaceAll("'","'\\''")+"'";
export class Manager{
 constructor(root){
  this.root=root;this.runtime=path.join(root,'runtime');this.socket='switchboard-'+crypto.createHash('sha256').update(root).digest('hex').slice(0,12);
  this.claude=process.env.SWITCHBOARD_CLAUDE||path.join(os.homedir(),'.local/bin/claude');
  this.tmux=process.env.SWITCHBOARD_TMUX||'tmux';this.jobs=new Map();this.refreshing=false;this.switching=false;
  fs.mkdirSync(root,{recursive:true,mode:0o700});fs.chmodSync(root,0o700);fs.mkdirSync(this.runtime,{recursive:true,mode:0o700});
  const keyFile=path.join(root,'vault.key');if(!fs.existsSync(keyFile))fs.writeFileSync(keyFile,crypto.randomBytes(32),{mode:0o600});this.key=fs.readFileSync(keyFile);
  this.state=readJSON(path.join(root,'state.json'),{accounts:[],sessions:[],activeId:null,autoSwitch:false,threshold:95,events:[]});
 }
 save(){atomicJSON(path.join(this.root,'state.json'),this.state)}
 event(message){this.state.events.unshift({at:new Date().toISOString(),message});this.state.events=this.state.events.slice(0,100);this.save()}
 async tm(...args){return (await exec(this.tmux,['-L',this.socket,...args],{env:cleanEnv(process.env,this.runtime),timeout:15000,maxBuffer:1024*1024})).stdout}
 getAccount(id){const a=this.state.accounts.find(a=>a.id===id);if(!a)throw Error('Account not found');return a}
 credentials(id){return unseal(readJSON(path.join(this.root,'vault',id+'.json')),this.key)}
 async verifyAccount(id){
  const a=this.getAccount(id);if(this.checkingAccount)throw Error('A connection check is already running');
  this.checkingAccount=id;const fingerprint=a.fingerprint;
  try{
   const result=await checkConnection(this.claude,this.credentials(id));
   if(this.getAccount(id).fingerprint!==fingerprint)throw Error('Credential changed during the check; check the new credential again.');
   a.connectionCheck={...result,at:new Date().toISOString()};
   if(result.ok){a.auth='ok';a.authErrorAt=null}else if(result.expired){a.auth='expired';a.authErrorAt=Date.now()}
   this.event(`Connection check ${result.ok?'passed':'did not pass'}: ${a.name}`);return a.connectionCheck;
  }finally{this.checkingAccount=null}
 }
 async addAccount({name,token,expiresAt=null,scopes=null,replaceId=null}){
  name=String(name||'').trim();if(!name||name.length>100)throw Error('Enter an account name (1–100 characters)');
  if(typeof token!=='string'||!/^sk-ant-oat\d+-[A-Za-z0-9_-]+$/.test(token.trim()))throw Error('Enter an OAuth token generated by official Claude Code');
  token=token.trim();const fingerprint=crypto.createHash('sha256').update(token).digest('hex');
  let a=this.state.accounts.find(a=>a.fingerprint===fingerprint);
  if(a&&a.id!==replaceId)throw Error('This credential is already registered');
  const previous=replaceId?this.getAccount(replaceId):null;
  if(previous?.id===this.state.activeId&&this.state.sessions.some(s=>s.running&&readJSON(path.join(this.root,'activity',s.id+'.json'))?.busy))throw Error('Wait for managed responses to finish before renewing the selected account');
  a={id:previous?.id||crypto.randomUUID(),name,enabled:previous?.enabled??true,auth:'unverified',expiresAt:typeof expiresAt==='number'?expiresAt:null,fingerprint,windows:[],observedAt:null};
  atomicJSON(path.join(this.root,'vault',a.id+'.json'),seal({accessToken:token,expiresAt:a.expiresAt,scopes:scopes||['user:inference']},this.key));
  if(previous)this.state.accounts[this.state.accounts.indexOf(previous)]=a;else this.state.accounts.push(a);
  this.event(`${previous?'Renewed':'Added'} ${name}`);await this.refreshAccount(a);
  if(previous?.id===this.state.activeId)await this.switchTo(a.id,'Credential renewed');this.save();return a.id;
 }
 async refreshAccount(a){
  if(a.expiresAt&&a.expiresAt<Date.now()){a.auth='expired';a.error='Credential expired. Connect this account again.';return}
  if(a.retryAt&&a.retryAt>Date.now())return;
  try{
   const r=await fetch('https://api.anthropic.com/api/oauth/usage',{headers:{Authorization:'Bearer '+this.credentials(a.id).accessToken,'anthropic-beta':'oauth-2025-04-20','User-Agent':'local-switchboard/0.1'},signal:AbortSignal.timeout(10000)});
   if(r.status===429){a.retryAt=Date.now()+retryDelay(r.headers.get('retry-after'));a.error='Usage endpoint is rate limited; waiting before retry.';return}
   if(r.status===401){a.auth='expired';a.authErrorAt=Date.now();a.error='Login needs renewal';return}
   if(r.status===403){a.retryAt=Date.now()+15*60000;a.error='This credential cannot read quota (HTTP 403). Test connection separately; retrying quota in 15 minutes.';return}
   if(!r.ok){a.auth=a.auth==='ok'?'ok':'usage-unavailable';a.error='Usage unavailable for this credential (HTTP '+r.status+'). Session usage can update after a response.';return}
   const windows=windowsFromUsage(await r.json());if(!windows.length)throw Error('No usage windows');
   a.windows=windows;a.observedAt=new Date().toISOString();a.auth='ok';a.error=null;a.retryAt=null;
  }catch{a.error='Usage refresh failed; showing last observation.'}
 }
 async refresh(){if(this.refreshing)return;this.refreshing=true;try{await Promise.allSettled(this.state.accounts.map(a=>this.refreshAccount(a)));this.save();await this.tick()}finally{this.refreshing=false}}
 async switchTo(id,reason='Manual switch'){
  if(this.switching)throw Error('A switch is already in progress');this.switching=true;
  try{
   const a=this.getAccount(id);if(!a.enabled)throw Error('Enable this account first');if(a.auth==='expired')throw Error('Reconnect this account before switching');
   const oauth=this.credentials(id);if(oauth.expiresAt&&oauth.expiresAt<Date.now()+60000)throw Error('Credential expired');
   const busy=this.state.sessions.filter(s=>s.running&&readJSON(path.join(this.root,'activity',s.id+'.json'))?.busy);
   if(busy.length)throw Error('A managed session is working. Switch after its response finishes.');
   const from=this.state.activeId;
   // A pasted setup token has no machine-readable expiration. Do not impose a
   // one-day client expiry; native setup tokens are long-lived. The server remains
   // authoritative and a 401 marks the account as needing renewal sooner.
   atomicJSON(path.join(this.runtime,'.credentials.json'),{claudeAiOauth:{...oauth,expiresAt:oauth.expiresAt||Date.now()+365*86400000}});
   this.state.activeId=id;this.state.lastSwitchAt=Date.now();
   atomicJSON(path.join(this.runtime,'active.json'),{id,name:a.name,at:Date.now()});
   this.event(`${reason}: ${from?this.getAccount(from).name:'none'} → ${a.name}`);
  }finally{this.switching=false}
 }
 settings(){return {statusLine:{type:'command',command:`${quote(process.execPath)} ${quote(path.join(import.meta.dirname,'statusline.mjs'))} ${quote(this.root)}`},hooks:{UserPromptSubmit:[{hooks:[{type:'command',command:`${quote(process.execPath)} ${quote(path.join(import.meta.dirname,'activity.mjs'))} ${quote(this.root)} start`}]}],Stop:[{hooks:[{type:'command',command:`${quote(process.execPath)} ${quote(path.join(import.meta.dirname,'activity.mjs'))} ${quote(this.root)} stop`}]}]}}}
 async launch({cwd,model='sonnet'}){
  if(!path.isAbsolute(cwd||'')||!fs.statSync(cwd).isDirectory())throw Error('Choose an existing absolute workspace directory');
  cwd=fs.realpathSync(cwd);
  if(!['haiku','sonnet','opus'].includes(model))throw Error('Choose haiku, sonnet, or opus');
  if(!this.state.activeId)throw Error('Select an account first');
  const a=this.getAccount(this.state.activeId);if(a.auth==='expired')throw Error('Selected account needs renewal');
  const configFile=path.join(this.runtime,'.claude.json');
  const config=readJSON(configFile,{});
  // The account has already been connected. Skip only first-run account/theme
  // onboarding; workspace trust and tool permission prompts remain native.
  if(!config.hasCompletedOnboarding)atomicJSON(configFile,{...config,hasCompletedOnboarding:true,theme:config.theme||'dark'});
  // A Keychain item must never be created for this shared runtime. Enrollment uses a separate directory.
  atomicJSON(path.join(this.runtime,'settings.json'),this.settings());
  const id=crypto.randomUUID(),name='session-'+id.slice(0,8);
  await this.tm('new-session','-d','-s',name,'-x','120','-y','36','-c',cwd,this.claude,'--no-chrome','--model',model,'--session-id',id);
  const s={id,name,cwd,model,running:true,createdAt:new Date().toISOString()};this.state.sessions.push(s);this.event(`Started ${name}`);return s;
 }
 async sessionScreen(id){const s=this.state.sessions.find(s=>s.id===id);if(!s)throw Error('Session not found');return redact(await this.tm('capture-pane','-p','-J','-t',s.name,'-S','-70'))}
 async send(id,text,key){const s=this.state.sessions.find(s=>s.id===id);if(!s)throw Error('Session not found');
  if(key){if(!['Enter','Escape','Up','Down','C-c'].includes(key))throw Error('Invalid key');await this.tm('send-keys','-t',s.name,key)}
  else{if(typeof text!=='string'||text.length>10000||/[\x00-\x08\x0b-\x1f]/.test(text))throw Error('Invalid message');if(/^\s*\/(login|logout)\b/i.test(text))throw Error('Use Connect account in the dashboard to preserve file-based switching');await this.tm('send-keys','-t',s.name,'-l',text);await this.tm('send-keys','-t',s.name,'Enter')}
 }
 async stopSession(id){const s=this.state.sessions.find(s=>s.id===id);if(!s)throw Error('Session not found');if(readJSON(path.join(this.root,'activity',id+'.json'))?.busy)throw Error('Interrupt the running task in its terminal first');try{await this.tm('kill-session','-t',s.name)}catch{}s.running=false;this.event(`Stopped ${s.name}; conversation retained`)}
 archiveSession(id){const s=this.state.sessions.find(s=>s.id===id);if(!s)throw Error('Session not found');if(s.running)throw Error('Stop the session before archiving');this.state.sessions=this.state.sessions.filter(s=>s.id!==id);this.event(`Archived ${s.name}; conversation retained`)}
 async tick(){
  if(this.ticking)return;this.ticking=true;
  try{
   for(const s of this.state.sessions){try{await this.tm('has-session','-t',s.name);s.running=true}catch{s.running=false}
    if(!s.running)continue;
    const transcript=path.join(this.runtime,'projects',s.cwd.replace(/[^A-Za-z0-9]/g,'-'),s.id+'.jsonl');
    if(fs.existsSync(transcript)){
     const fd=fs.openSync(transcript,'r');let tail;try{const size=fs.fstatSync(fd).size;const buf=Buffer.alloc(Math.min(size,65536));fs.readSync(fd,buf,0,buf.length,size-buf.length);tail=buf.toString()}finally{fs.closeSync(fd)}
     const messages=tail.split('\n').flatMap(l=>{try{return [JSON.parse(l)]}catch{return []}});
     const last=messages.filter(m=>m.type==='assistant').at(-1);
     if(last?.message?.model==='<synthetic>'&&last.message.id!==s.handledErrorId){
      const text=last.message.content?.filter(c=>c.type==='text').map(c=>c.text).join(' ')||'';
      const limited=/hit your .*limit|reached your .*limit|usage limit|rate.limit|429/i.test(text);
      const authError=/401|invalid bearer|authentication failed/i.test(text);
      if(limited||authError){
       const activity=readJSON(path.join(this.root,'activity',s.id+'.json'));
       if(activity?.accountId===this.state.activeId){
        const a=this.getAccount(activity.accountId);
        if(limited){a.limitDetectedAt=Date.now();a.cooldownUntil=Date.now()+300000;}
        else{a.auth='expired';a.authErrorAt=Date.now()}
        s.waitingForAccount=true;s.failedAccountId=a.id;s.handledErrorId=last.message.id;
        atomicJSON(path.join(this.root,'activity',s.id+'.json'),{...activity,busy:false});
        this.event(`${s.name}: ${limited?'usage limit':'authentication error'} on ${a.name}`);
       }
      }
     }
    }
   }
   // Status-line telemetry has no credentials and only records documented quota fields.
   for(const s of this.state.sessions){const sample=readJSON(path.join(this.root,'telemetry',s.id+'.json'));if(!sample||sample.accountId!==this.state.activeId||sample.at<=(this.state.lastSwitchAt||0))continue;const a=this.getAccount(sample.accountId);if(sample.at<=(a.authErrorAt||0)||sample.at<=(a.limitDetectedAt||0)||(a.expiresAt&&a.expiresAt<=Date.now()))continue;if(!a.observedAt||sample.at>Date.parse(a.observedAt)){a.windows=mergeWindows(a.windows,sample.windows,a.observedAt,new Date(sample.at).toISOString());a.observedAt=new Date(sample.at).toISOString();a.auth='ok';a.error=null}}
   if(this.state.autoSwitch&&this.state.activeId&&Date.now()-(this.state.lastSwitchAt||0)>60000){
    const a=this.getAccount(this.state.activeId);
    const stale=!a.observedAt||Date.now()-Date.parse(a.observedAt)>300000;
    const full=!stale&&a.windows.some(w=>w.used>=this.state.threshold);
    if(full||a.auth==='expired'||(a.limitDetectedAt&&Date.now()-a.limitDetectedAt<300000)){
     const next=chooseAccount(this.state.accounts,a.id,this.state.threshold);
     if(next){try{await this.switchTo(next.id,'Automatic switch')}catch{/* Wait for response completion. */}}
    }
   }
   if(this.state.autoSwitch&&Date.now()-(this.state.lastSwitchAt||0)>35000){
    for(const s of this.state.sessions.filter(s=>s.running&&s.waitingForAccount&&s.failedAccountId!==this.state.activeId)){
     const screen=await this.sessionScreen(s.id);
     // Only resume a clean, idle prompt. Never overwrite a user's draft or interrupt a running command.
     const lines=screen.split('\n');const prompt=lines.filter(l=>l.trimStart().startsWith('❯')).at(-1);
     if(prompt&&/^\s*❯\s*$/.test(prompt)&&!readJSON(path.join(this.root,'activity',s.id+'.json'))?.busy){s.waitingForAccount=false;await this.send(s.id,'Continue the previous task.');this.event(`Resumed ${s.name} after account switch`)}
    }
   }
   this.save();
  }finally{this.ticking=false}
 }
 async startLogin(name,replaceId=null){
  if(this.jobs.size)throw Error('Finish or cancel the existing sign-in first');
  if(!String(name||'').trim())throw Error('Enter an account name');
  const id=crypto.randomUUID(),dir=path.join(this.root,'enrollment',id),target='login-'+id.slice(0,8);fs.mkdirSync(dir,{recursive:true,mode:0o700});
  const env=cleanEnv(process.env,dir);
  await exec(this.tmux,['-L',this.socket,'new-session','-d','-s',target,'-x','240','-y','40','-c',dir,'env',`CLAUDE_CONFIG_DIR=${dir}`,this.claude,'setup-token'],{env,timeout:15000});
  await this.tm('set-option','-w','-t',target,'remain-on-exit','on');
  if(replaceId)this.getAccount(replaceId);
  this.jobs.set(id,{id,name:String(name).slice(0,100),target,dir,replaceId,createdAt:Date.now()});return id;
 }
 async loginStatus(id){
  const job=this.jobs.get(id);if(!job)throw Error('Sign-in not found');if(job.completing)return {id,state:'pending',screen:'Saving the new credential…'};
  let screen='';try{screen=await this.tm('capture-pane','-p','-J','-t',job.target,'-S','-200')}catch{return {id,state:'closed',screen:'Sign-in terminal closed. You can paste a token generated with claude setup-token instead.'}}
  const token=screen.match(/sk-ant-oat\d+-[A-Za-z0-9_-]{40,}/)?.[0];
  if(token){job.completing=true;try{const accountId=await this.addAccount({name:job.name,token,replaceId:job.replaceId});await this.cancelLogin(id);return {id,state:'complete',accountId}}catch(e){job.completing=false;throw e}}
  const url=screen.match(/https:\/\/(?:claude\.ai|claude\.com|platform\.claude\.com)\/[^\s]+/)?.[0];
  return {id,state:'pending',url:url||null,screen:redact(screen)};
 }
 async loginInput(id,text){const job=this.jobs.get(id);if(!job)throw Error('Sign-in not found');if(typeof text!=='string'||text.length>3000||/[\r\n\x00-\x1f]/.test(text))throw Error('Invalid code');if(text)await this.tm('send-keys','-t',job.target,'-l',text);await this.tm('send-keys','-t',job.target,'Enter')}
 async cancelLogin(id){const job=this.jobs.get(id);if(!job)return;try{await this.tm('kill-session','-t',job.target)}catch{}this.jobs.delete(id)}
 snapshot(){return {activeId:this.state.activeId,autoSwitch:this.state.autoSwitch,threshold:this.state.threshold,refreshing:this.refreshing,accounts:this.state.accounts.map(({fingerprint,...a})=>({...a,eligible:!!eligible(a,this.state.threshold)})),sessions:this.state.sessions.map(s=>({...s,activity:readJSON(path.join(this.root,'activity',s.id+'.json')),attach:`tmux -L ${this.socket} attach -t ${s.name}`})),events:this.state.events,loginJobs:[...this.jobs.values()].map(j=>({id:j.id,name:j.name}))}}
}
